# Desafio Data Science - Semana 1

## Importação do arquivo de dados

In [473]:
import pandas as pd

In [474]:
pd.set_option("display.max_columns", 100)

In [475]:
# leitura do arquivo json
dados = pd.read_json('dados/telco-customer-churn.json')

In [476]:
dados.head()

,customerID,Churn,customer,phone,internet,account
0,0002-ORFBO,No,"{'gender': 'Female', 'SeniorCitizen': 0, 'Part...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'One year', 'PaperlessBilling': '..."
1,0003-MKNFE,No,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'Yes'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
2,0004-TLHLJ,Yes,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
3,0011-IGKFF,Yes,"{'gender': 'Male', 'SeniorCitizen': 1, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
4,0013-EXCHZ,Yes,"{'gender': 'Female', 'SeniorCitizen': 1, 'Part...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."

In [477]:
# números de linhas e colunas
print('Total de linhas: ' + str(dados.shape[0]))
print('Total de colunas: ' + str(dados.shape[1]))

Total de linhas: 7267
Total de colunas: 6

## Normalização dos dados json

In [478]:
# normalizando a coluna customer
customer = pd.json_normalize(data=dados.customer)

In [479]:
# normalizando a coluna phone
phone = pd.json_normalize(data=dados.phone)

In [480]:
# normalizando a coluna internet
internet = pd.json_normalize(data=dados.internet)

In [481]:
# normalizando a coluna account
account = pd.json_normalize(data=dados.account)

In [482]:
# juntando os dataframes
dados_combinados = pd.concat([dados, customer, phone, internet, account], axis=1)

In [483]:
# eliminando colunas redundantes
dados_combinados = dados_combinados.drop(['customer', 'phone', 'internet', 'account'], axis=1)
dados_combinados.head()

,customerID,Churn,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,Charges.Monthly,Charges.Total
0,0002-ORFBO,No,Female,0,Yes,Yes,9,Yes,No,DSL,No,Yes,No,Yes,Yes,No,One year,Yes,Mailed check,65.6,593.3
1,0003-MKNFE,No,Male,0,No,No,9,Yes,Yes,DSL,No,No,No,No,No,Yes,Month-to-month,No,Mailed check,59.9,542.4
2,0004-TLHLJ,Yes,Male,0,No,No,4,Yes,No,Fiber optic,No,No,Yes,No,No,No,Month-to-month,Yes,Electronic check,73.9,280.85
3,0011-IGKFF,Yes,Male,1,Yes,No,13,Yes,No,Fiber optic,No,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,98.0,1237.85
4,0013-EXCHZ,Yes,Female,1,Yes,No,3,Yes,No,Fiber optic,No,No,No,Yes,Yes,No,Month-to-month,Yes,Mailed check,83.9,267.4

## Análise do DataFrame

In [484]:
# pesquisar dados nulos
dados_combinados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7267 non-null   object
 1   Churn             7267 non-null   object
 2   gender            7267 non-null   object
 3   SeniorCitizen     7267 non-null   int64
 4   Partner           7267 non-null   object
 5   Dependents        7267 non-null   object
 6   tenure            7267 non-null   int64
 7   PhoneService      7267 non-null   object
 8   MultipleLines     7267 non-null   object
 9   InternetService   7267 non-null   object
 10  OnlineSecurity    7267 non-null   object
 11  OnlineBackup      7267 non-null   object
 12  DeviceProtection  7267 non-null   object
 13  TechSupport       7267 non-null   object
 14  StreamingTV       7267 non-null   object
 15  StreamingMovies   7267 non-null   object
 16  Contract          7267 non-null   object
 17  PaperlessBilling  7267 non-null   object
 18  PaymentMethod     7267 non-null   object
 19  Charges.Monthly   7267 non-null   float64
 20  Charges.Total     7267 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.2+ MB

In [485]:
# analisando os dados das colunas
for column in dados_combinados.columns:
    print(column, dados_combinados[column].unique())

customerID ['0002-ORFBO' '0003-MKNFE' '0004-TLHLJ' ... '9992-UJOEL' '9993-LHIEB'
 '9995-HOTOH']
Churn ['No' 'Yes' '']
gender ['Female' 'Male']
SeniorCitizen [0 1]
Partner ['Yes' 'No']
Dependents ['Yes' 'No']
tenure [ 9  4 13  3 71 63  7 65 54 72  5 56 34  1 45 50 23 55 26 69 11 37 49 66
 67 20 43 59 12 27  2 25 29 14 35 64 39 40  6 30 70 57 58 16 32 33 10 21
 61 15 44 22 24 19 47 62 46 52  8 60 48 28 41 53 68 51 31 36 17 18 38 42
  0]
PhoneService ['Yes' 'No']
MultipleLines ['No' 'Yes' 'No phone service']
InternetService ['DSL' 'Fiber optic' 'No']
OnlineSecurity ['No' 'Yes' 'No internet service']
OnlineBackup ['Yes' 'No' 'No internet service']
DeviceProtection ['No' 'Yes' 'No internet service']
TechSupport ['Yes' 'No' 'No internet service']
StreamingTV ['Yes' 'No' 'No internet service']
StreamingMovies ['No' 'Yes' 'No internet service']
Contract ['One year' 'Month-to-month' 'Two year']
PaperlessBilling ['Yes' 'No']
PaymentMethod ['Mailed check' 'Electronic check' 'Credit card (automatic)'
 'Bank transfer (automatic)']
Charges.Monthly [65.6  59.9  73.9  ... 91.75 68.8  67.85]
Charges.Total ['593.3' '542.4' '280.85' ... '742.9' '4627.65' '3707.6']

In [486]:
# convertendo a coluna charges.total para float
dados_combinados['Charges.Total'] = pd.to_numeric(dados_combinados['Charges.Total'], errors='coerce').fillna(0.0)

In [487]:
# total de registros cujo valor em Churn é vazio
churn_vazio = dados_combinados.Churn == ''
dados_combinados[churn_vazio].shape[0]

224

In [488]:
# eliminando registros cujo valor em Churn é vazio
dados_combinados.drop(dados_combinados[churn_vazio].index, inplace=True)
dados_combinados

,customerID,Churn,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,Charges.Monthly,Charges.Total
0,0002-ORFBO,No,Female,0,Yes,Yes,9,Yes,No,DSL,No,Yes,No,Yes,Yes,No,One year,Yes,Mailed check,65.60,593.30
1,0003-MKNFE,No,Male,0,No,No,9,Yes,Yes,DSL,No,No,No,No,No,Yes,Month-to-month,No,Mailed check,59.90,542.40
2,0004-TLHLJ,Yes,Male,0,No,No,4,Yes,No,Fiber optic,No,No,Yes,No,No,No,Month-to-month,Yes,Electronic check,73.90,280.85
3,0011-IGKFF,Yes,Male,1,Yes,No,13,Yes,No,Fiber optic,No,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,98.00,1237.85
4,0013-EXCHZ,Yes,Female,1,Yes,No,3,Yes,No,Fiber optic,No,No,No,Yes,Yes,No,Month-to-month,Yes,Mailed check,83.90,267.40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7262,9987-LUTYD,No,Female,0,No,No,13,Yes,No,DSL,Yes,No,No,Yes,No,No,One year,No,Mailed check,55.15,742.90
7263,9992-RRAMN,Yes,Male,0,Yes,No,22,Yes,Yes,Fiber optic,No,No,No,No,No,Yes,Month-to-month,Yes,Electronic check,85.10,1873.70
7264,9992-UJOEL,No,Male,0,No,No,2,Yes,No,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,50.30,92.75
7265,9993-LHIEB,No,Male,0,Yes,Yes,67,Yes,No,DSL,Yes,No,Yes,Yes,No,Yes,Two year,No,Mailed check,67.85,4627.65
7266,9995-HOTOH,No,Male,0,Yes,Yes,63,No,No phone service,DSL,Yes,Yes,Yes,No,Yes,Yes,Two year,No,Electronic check,59.00,3707.60

In [489]:
# reindexando o dataframe
new_index = range(dados_combinados.shape[0])
dados_combinados.index = new_index
dados_combinados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   Churn             7043 non-null   object
 2   gender            7043 non-null   object
 3   SeniorCitizen     7043 non-null   int64
 4   Partner           7043 non-null   object
 5   Dependents        7043 non-null   object
 6   tenure            7043 non-null   int64
 7   PhoneService      7043 non-null   object
 8   MultipleLines     7043 non-null   object
 9   InternetService   7043 non-null   object
 10  OnlineSecurity    7043 non-null   object
 11  OnlineBackup      7043 non-null   object
 12  DeviceProtection  7043 non-null   object
 13  TechSupport       7043 non-null   object
 14  StreamingTV       7043 non-null   object
 15  StreamingMovies   7043 non-null   object
 16  Contract          7043 non-null   object
 17  PaperlessBilling  7043 non-null   object
 18  PaymentMethod     7043 non-null   object
 19  Charges.Monthly   7043 non-null   float64
 20  Charges.Total     7043 non-null   float64
dtypes: float64(2), int64(2), object(17)
memory usage: 1.1+ MB

## Tradução das colunas

In [490]:
#traduzindo as colunas
colunas_traduzidas = ['Id Cliente', 'Cancelado', 'Gênero', 'Maior igual a 65', 'Parceiro', 'Dependentes', 
'Meses de contrato', 'Serviço telefônico', 'Múltiplas linhas', 'Serviço de internet', 'Segurança online', 
'Backup online', 'Proteção do dispositivo', 'Suporte técnico', 'TV a cabo', 'Streaming de filmes', 
'Tipo de contrato', 'Fatura online', 'Forma de pagamento', 'Valor por mês', 'Valor total']
dados_combinados.columns = colunas_traduzidas

In [491]:
# traduzindo os valores nas colunas
colunas_valores = {
    ('Cancelado', 'Parceiro', 'Dependentes', 'Serviço telefônico', 'Fatura online'): {
        'Yes': 'Sim',
        'No': 'Não'
    },
    ('Gênero', ): {
        'Female': 'Feminino',
        'Male': 'Masculino'
    },
    ('Serviço de internet', ): {
        'DSL': 'DSL',
        'Fiber optic': 'Fibra Ótica',
        'No': 'Não'
    },
    ('Segurança online', 'Backup online', 'Proteção do dispositivo', 
    'Suporte técnico', 'TV a cabo', 'Streaming de filmes'): {
        'No': 'Não',
        'Yes': 'Sim',
        'No internet service': 'Sem internet'
    },
    ('Tipo de contrato', ): {
        'One year': 'Anual',
        'Month-to-month': 'Mensal',
        'Two year': '2 anos'
    },
    ('Forma de pagamento', ): {
        'Mailed check': 'Cheque enviado',
        'Electronic check': 'Cheque eletrônico',
        'Credit card (automatic)': 'Cartão de crédito',
        'Bank transfer (automatic)': 'Transferência bancária'
    },
    ('Múltiplas linhas', ): {
        'No': 'Não',
        'Yes': 'Sim',
        'No phone service': 'Sem telefone'
    },
    ('Maior igual a 65', ): {
        0: 'Não',
        1: 'Sim'
    }
}
for colunas, value in colunas_valores.items():
    for coluna in colunas:
        dados_combinados[coluna] = dados_combinados[coluna].map(value)
dados_combinados.head()

,Id Cliente,Cancelado,Gênero,Maior igual a 65,Parceiro,Dependentes,Meses de contrato,Serviço telefônico,Múltiplas linhas,Serviço de internet,Segurança online,Backup online,Proteção do dispositivo,Suporte técnico,TV a cabo,Streaming de filmes,Tipo de contrato,Fatura online,Forma de pagamento,Valor por mês,Valor total
0,0002-ORFBO,Não,Feminino,Não,Sim,Sim,9,Sim,Não,DSL,Não,Sim,Não,Sim,Sim,Não,Anual,Sim,Cheque enviado,65.6,593.30
1,0003-MKNFE,Não,Masculino,Não,Não,Não,9,Sim,Sim,DSL,Não,Não,Não,Não,Não,Sim,Mensal,Não,Cheque enviado,59.9,542.40
2,0004-TLHLJ,Sim,Masculino,Não,Não,Não,4,Sim,Não,Fibra Ótica,Não,Não,Sim,Não,Não,Não,Mensal,Sim,Cheque eletrônico,73.9,280.85
3,0011-IGKFF,Sim,Masculino,Sim,Sim,Não,13,Sim,Não,Fibra Ótica,Não,Sim,Sim,Não,Sim,Sim,Mensal,Sim,Cheque eletrônico,98.0,1237.85
4,0013-EXCHZ,Sim,Feminino,Sim,Sim,Não,3,Sim,Não,Fibra Ótica,Não,Não,Não,Sim,Sim,Não,Mensal,Sim,Cheque enviado,83.9,267.40

## Inclusão de coluna extra

In [492]:
# incluindo a coluna Gastos diários
dados_combinados.insert(19, 'Gastos diários', value=round(dados_combinados['Valor por mês']/30, 2))
dados_combinados

,Id Cliente,Cancelado,Gênero,Maior igual a 65,Parceiro,Dependentes,Meses de contrato,Serviço telefônico,Múltiplas linhas,Serviço de internet,Segurança online,Backup online,Proteção do dispositivo,Suporte técnico,TV a cabo,Streaming de filmes,Tipo de contrato,Fatura online,Forma de pagamento,Gastos diários,Valor por mês,Valor total
0,0002-ORFBO,Não,Feminino,Não,Sim,Sim,9,Sim,Não,DSL,Não,Sim,Não,Sim,Sim,Não,Anual,Sim,Cheque enviado,2.19,65.60,593.30
1,0003-MKNFE,Não,Masculino,Não,Não,Não,9,Sim,Sim,DSL,Não,Não,Não,Não,Não,Sim,Mensal,Não,Cheque enviado,2.00,59.90,542.40
2,0004-TLHLJ,Sim,Masculino,Não,Não,Não,4,Sim,Não,Fibra Ótica,Não,Não,Sim,Não,Não,Não,Mensal,Sim,Cheque eletrônico,2.46,73.90,280.85
3,0011-IGKFF,Sim,Masculino,Sim,Sim,Não,13,Sim,Não,Fibra Ótica,Não,Sim,Sim,Não,Sim,Sim,Mensal,Sim,Cheque eletrônico,3.27,98.00,1237.85
4,0013-EXCHZ,Sim,Feminino,Sim,Sim,Não,3,Sim,Não,Fibra Ótica,Não,Não,Não,Sim,Sim,Não,Mensal,Sim,Cheque enviado,2.80,83.90,267.40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,9987-LUTYD,Não,Feminino,Não,Não,Não,13,Sim,Não,DSL,Sim,Não,Não,Sim,Não,Não,Anual,Não,Cheque enviado,1.84,55.15,742.90
7039,9992-RRAMN,Sim,Masculino,Não,Sim,Não,22,Sim,Sim,Fibra Ótica,Não,Não,Não,Não,Não,Sim,Mensal,Sim,Cheque eletrônico,2.84,85.10,1873.70
7040,9992-UJOEL,Não,Masculino,Não,Não,Não,2,Sim,Não,DSL,Não,Sim,Não,Não,Não,Não,Mensal,Sim,Cheque enviado,1.68,50.30,92.75
7041,9993-LHIEB,Não,Masculino,Não,Sim,Sim,67,Sim,Não,DSL,Sim,Não,Sim,Sim,Não,Sim,2 anos,Não,Cheque enviado,2.26,67.85,4627.65
7042,9995-HOTOH,Não,Masculino,Não,Sim,Sim,63,Não,Sem telefone,DSL,Sim,Sim,Sim,Não,Sim,Sim,2 anos,Não,Cheque eletrônico,1.97,59.00,3707.60

## Salvando o DataFrame

In [493]:
# salvando o DataFrame
dados_combinados.to_csv('Dados/dados_tratados.csv', index=False)